### ISSUE TITLE
Taskwarrior tab completion

### ISSUE THREAD

**Issue by grovesteyn** [xonsh/xonsh#1619]
Hi

I am using taskwarrior on xonsh.  The tab completion brings up the correct options, but when an option is selected it completely replaces the current "word" rather than just adding it to the end.  For example:
`task add Test proj:<tab>`
... generates the appropriate list of names.  But, when I select the appropriate name it also replaces the `proj:` part, rather than just adding it to the end of the line.

Regards

Grové

**Comment by gforsyth** [comment]
Thanks for reporting @grovesteyn !  I can confirm this bug.  It's a little weird to me that this is happening -- we only split completion tokens on spaces and `task` has bash completions, so we are sending in the token `proj:` and receiving a list of projects back but it should know better than to overwrite... but I guess not?

**Comment by scopatz** [comment]
So I have noticed this too.  However, it seems to only happen when you use the arrow keys to scroll through the selections and then press enter.  It you scroll through by hitting tab, everything works fine.  

This seems to be an issue on our end somehow. IPython has the behaviour one would expect.

**Comment by grovesteyn** [comment]
I have the same problem - even when using tab. (xonsh 0.4.5).

**Comment by blahgeek** [comment]
@grovesteyn This issue should be fixed in current master (after #1662 I believe) via a new implementation of bash completion system. Could you try it again?

**Comment by grovesteyn** [comment]
@blahgeek I did a quick test and it seems to work perfectly.  Excellent!

Thanks.

**Comment by grovesteyn** [comment]
I have just upgraded from Ubuntu 14.04 to 16.04 and am running xonsh 0.4.7 from PyPI.  I again have the same problem as described in my initial comment on 24 August.  Any ideas?

**Comment by blahgeek** [comment]
Hi @grovesteyn , I didn't have this problem on either master or 0.4.7 on macOS. Could you please post your output of `xonfig` here? Thanks!

**Comment by grovesteyn** [comment]
My xonfig output is as follows:

`+------------------+-----------------+
| xonsh            | 0.4.7           |
| Git SHA          | None            |
| Python           | 3.5.2           |
| PLY              | 3.9             |
| have readline    | True            |
| prompt toolkit   | None            |
| shell type       | readline        |
| pygments         | 2.1             |
| on posix         | True            |
| on linux         | True            |
| distro           | Ubuntu          |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
`

**Comment by grovesteyn** [comment]
My xconfig output is as follows:

+------------------+-----------------+
| xonsh            | 0.4.7           |
| Git SHA          | None            |
| Python           | 3.5.2           |
| PLY              | 3.9             |
| have readline    | True            |
| prompt toolkit   | None            |
| shell type       | readline        |
| pygments         | 2.1             |
| on posix         | True            |
| on linux         | True            |
| distro           | Ubuntu          |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+

**Comment by grovesteyn** [comment]
I think I found the problem.  I did a:
 sudo pip3 install --upgrade  xonsh[ptk, proctitle]
which solved the problem.

Before this I had the old bash-like tab completion where the options were listed above the cursor and it was not possible to tab through them as it is with PTK.  In this case the tab completion still replaced the part before pressing TAB as explained in my first post above.  In other words, it appears to still have this bug without PTK installed.

**Comment by blahgeek** [comment]
Thanks for your information!

So it's only happening while using readline, that make sense. I'll see what I can do here.

**Comment by grovesteyn** [comment]
Yes - exactly.  Good luck.

**Comment by scopatz** [comment]
I believe that this has been fixed on master for some time now.  Please feel free to reopen if you continue to see this issue.

**Comment by grovesteyn** [comment]
This issue (as described above) still exists in the latest version.

Ubuntu 20.04
`
+------------------+----------------------------------+
| xonsh            | 0.9.24                           |
| Python           | 3.8.5                            |
| PLY              | 3.11                             |
| have readline    | True                             |
| prompt toolkit   | 3.0.5                            |
| shell type       | prompt_toolkit                   |
| pygments         | 2.3.1                            |
| on posix         | True                             |
| on linux         | True                             |
| distro           | ubuntu                           |
| on darwin        | False                            |
| on windows       | False                            |
| on cygwin        | False                            |
| on msys2         | False                            |
| is superuser     | False                            |
| default encoding | utf-8                            |
| xonsh encoding   | utf-8                            |
| encoding errors  | surrogateescape                  |
| on jupyter       | True                             |
| jupyter kernel   | /usr/share/jupyter/kernels/xonsh |
+------------------+----------------------------------+`

Would be great to get it working.

**Comment by grovesteyn** [comment]
This issue still exists as described above.  Would be great to get it working.

Ubuntu 20.04

xconfig output:
+------------------+----------------------------------+
| xonsh            | 0.9.24                           |
| Python           | 3.8.5                            |
| PLY              | 3.11                             |
| have readline    | True                             |
| prompt toolkit   | 3.0.5                            |
| shell type       | prompt_toolkit                   |
| pygments         | 2.3.1                            |
| on posix         | True                             |
| on linux         | True                             |
| distro           | ubuntu                           |
| on darwin        | False                            |
| on windows       | False                            |
| on cygwin        | False                            |
| on msys2         | False                            |
| is superuser     | False                            |
| default encoding | utf-8                            |
| xonsh encoding   | utf-8                            |
| encoding errors  | surrogateescape                  |
| on jupyter       | True                             |
| jupyter kernel   | /usr/share/jupyter/kernels/xonsh |
+------------------+----------------------------------+
