### ISSUE TITLE
ls ANSI output looks screwy until clear

### ISSUE THREAD

**Issue by kirbyfan64** [xonsh/xonsh#2234]
Using the `l` as an alias for `ls --color=auto`, which `ls` being the version in GnuWin32:

![xonsh](https://cloud.githubusercontent.com/assets/1690697/23185212/3ec49a5c-f848-11e6-86f7-f1ce7e0e2b13.png)

Once I run `clear`, the output is correct.

**Comment by scopatz** [comment]
Hi @kirbyfan64, can you post the output of your xonfig, please? Just to be clear. Thanks for reporting!

**Comment by scopatz** [comment]
Also, I believe that this might have been fixed already by #2208

**Comment by kirbyfan64** [comment]
@scopatz 

```
{
 "xontribs": [
  "distributed"
 ]
}
```

Nothing too crazy.

Also, I just tried `pip install -U git+https://github.com/xonsh/xonsh.git` and re-started Xonsh, and the error still persists...

**Comment by gforsyth** [comment]
hey @kirbyfan64 -- I believe @scopatz was looking for the output of the command `xonfig`

**Comment by melund** [comment]
It works fine for me on master with the prompt_toolkit backend. 

![image](https://cloud.githubusercontent.com/assets/1038978/23186560/e2182fd6-f887-11e6-8ff9-3e0d7b4bb43b.png)

It should also be fixed for the readline backend on master.

**Comment by kirbyfan64** [comment]
@gforsyth Oops... *facepalm*

```
+------------------+----------------------+
| xonsh            | 0.5.5.dev120         |
| Git SHA          | fba07c5              |
| Commit Date      | Feb 21 14:50:42 2017 |
| Python           | 3.5.2                |
| PLY              | 3.9                  |
| have readline    | False                |
| prompt toolkit   | 1.0.7                |
| shell type       | prompt_toolkit       |
| pygments         | 2.1.3                |
| on posix         | False                |
| on linux         | False                |
| on darwin        | False                |
| on windows       | True                 |
| on cygwin        | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

**Comment by melund** [comment]
Ok. Looks like you are using PTK. I haven't seen a similar issue with PTK. @scopatz It could indicate that we need the fix for PTK as well. https://github.com/xonsh/xonsh/pull/2208#discussion_r101889363

**Comment by melund** [comment]
You could also try to update prompt_toolkit if you have the option. Maybe that solves it.

**Comment by scopatz** [comment]
Yeah, I agree, maybe we do need the fix for PTK.  @kirbyfan64 - can you please update PTK to v1.0.13 and verify that it is still broken. If so, we can put in a quick fix.

**Comment by kirbyfan64** [comment]
@scopatz Just tried PTK 1.0.13, and it's definitely still broken!

**Comment by scopatz** [comment]
Hey @kirbyfan64, can you try out #2238 and see if that fixes it?

**Comment by kirbyfan64** [comment]
Unfortunately, I seem to have hit this again with the latest version from Git (although now it's harder to reproduce):

![xonsh2](https://cloud.githubusercontent.com/assets/1690697/23320684/67c23d50-faa1-11e6-8161-64a8e82a5f9f.png)
![xonsh3](https://cloud.githubusercontent.com/assets/1690697/23320683/67c1c000-faa1-11e6-98e3-7df744e82e58.png)

**Comment by scopatz** [comment]
Hmm I bet certain commands are just resetting the terminal status.

**Comment by scopatz** [comment]
Hey @kirbyfan64, can you try out #2245 please and see if that fixes it?

**Comment by scopatz** [comment]
Please reopen if needed @kirbyfan64!
