### ISSUE TITLE
emacsclient -t and tmux

### ISSUE THREAD

**Issue by JohnLunzer** [xonsh/xonsh#2292]
You're thinking, wasn't there already an issue for this command. There was and I contemplated reopening that issue but I think this is different.

In `commands_cache.py` I have set `emacsclient` to `predict_false`. That setting should probably be set in master.

To start I've got my emacs daemon up and running and tested in other console windows. After updating to the most recent master, when I try to start `emacsclient -t myFile.py` for the first time in a new `xonsh` shell the command just kicks back to the console without starting my emacs windows. If I run the same command a second time then the emacs window opens and my file opens and then a couple seconds later a scratch buffer opens. This is all within tmux.

If I run the xonsh shell outside of tmux then enter the `emacsclient -t myFile.py` command it starts up the first time.

Full disclosure of details: I'm running spacemacs configuration of emacs. Haven't tested on vanilla emacs. But the failure point appears to be tmux interaction so I'm starting here.

**Comment by gforsyth** [comment]
Hey @JohnLunzer -- can you try updating spacemacs, both spacemacs itself and your packages? 
I believe this is an upstream issue that has been fixed recently.

**Comment by JohnLunzer** [comment]
@gforsyth Can you link me to that issue? 

I've updated my spacemacs (on the develop branch) and I've updated all my packages and I'm still getting the issue. I may be imaginging but it seems to be worse now as `emacsclient -t` will now start only about 10% of the time.

A newer detail is that when I start `emacsclient -t` if no daemon is running, it will start the daemon and start the client up every time for that first time. 

I've tested running in both xonsh and zsh outside of tmux and things are running smoothly.

**Comment by gforsyth** [comment]
Whoops.  Sorry, I glossed over the `tmux` part of that equation.  

Here's the issue: https://github.com/syl20bnr/spacemacs/issues/5219

This would be a workaround at best, but have you tried this with [pymux](https://github.com/jonathanslenders/pymux)? It may make no difference at all, but I'm curious.

**Comment by JohnLunzer** [comment]
My gut feeling is that the issue you listed is not the exact issue I am encountering but the behavior described is exactly what I am seeing and the workaround might be applicable.

That said, this feels like an interaction between `tmux` and `xonsh`. Some proof of that is that if I run `emacsclient -t` from `ranger` while within `tmux` then emacs starts fine every time. I also believe the issue occurred some time within the last month of `xonsh` development. When I switched to spacemacs 0.200 I didn't have an issue but when I updated `xonsh` recently is when the erroneous behavior started.

I have tried pymux and liked the features but I couldn't get it to register middle mouse button clicks, which is important because I use a remote desktop client that relies on the middle click for pasting text from host to client. 

Unless anyone has any clues to what might have changed I may have to bisect, but time is limited at the moment.

**Comment by gforsyth** [comment]
I think bisection is probably the best bet for helping us figure out what's going on.  There are a lot of moving parts here.

**Comment by JohnLunzer** [comment]
I experienced this issue on a system in which I haven't updated xonsh in a while. Xonfig:
```
+------------------+---------------------------------------------------+
| xonsh            | 0.4.7                                             |
| Git SHA          | 8f9e65f                                           |
| Commit Date      | Nov 16 05:38:08 2016                              |
| Python           | 3.5.2                                             |
| PLY              | 3.9                                               |
| have readline    | True                                              |
| prompt toolkit   | 1.0.9                                             |
| shell type       | prompt_toolkit                                    |
| pygments         | 2.1.3                                             |
| on posix         | True                                              |
| on linux         | <xonsh.lazyasd.LazyBool object at 0x7ff55a63bb00> |
| distro           | centos                                            |
| on darwin        | False                                             |
| on windows       | False                                             |
| on cygwin        | False                                             |
| is superuser     | True                                              |
| default encoding | utf-8                                             |
| xonsh encoding   | utf-8                                             |
| encoding errors  | surrogateescape                                   |
+------------------+---------------------------------------------------+
```
This system is also using vanilla emacs 23.1.1 (don't ask). Same behavior, but this time comes with an error message that perhaps was being hidden by my previous setup with spacemacs. Not every time but often when I get kicked back to xonsh I get this message printed on stdout:
```
*ERROR*: Assertion failed: (eq (match-end 0) (length string))
```
This is vanilla emacs with very little configuration (a few keybindings and faces changed), so I think we've removed the uncertainty that comes with spacemacs. 

In both cases the behavior sporadic, sometimes I don't hit it a whole day and somtimes I'll get the kickback behavior 10 times in a row. It does not seem to matter if I have a single or multiple `emacsclient` open.

Quick googling only found this thread from 2008:
https://lists.nongnu.org/archive/html/emacs-devel/2008-04/msg01592.html

A poster suggests activating the server-log but `(setq server-log t)` and then invoke the error I'm not getting a server log buffer.

I'm still fairly certain `xonsh` is a major player in what is going on, running `emacsclient -t` from `bash` has not invoked the kick back behavior in ~100 or so times I tried to run it, but in the same time-space I got the kick back behhavior in `xonsh`.

**Comment by anki-code** [comment]
hi @JohnLunzer! Does this still actual on the current xonsh 0.9.26?

**Comment by JohnLunzer** [comment]
> hi @JohnLunzer! Does this still actual on the current xonsh 0.9.26?

I'm sorry I can't confirm. It's been some time since I've been in an unrestricted environment that allows me to use xonsh.
