### ISSUE TITLE
using Vi in Xonsh, Esc key no longer works.

### ISSUE THREAD

**Issue by AGollapalli** [xonsh/xonsh#2382]
Using Arch Linux fully updated on Lenovo T520. 

After entering insert mode in vi in Xonsh, ex: editing a Crontab, the Esc key no longer works. it just prints "^[" when I hit "Esc". Vi in sh works just fine.

**Comment by gforsyth** [comment]
Hey @AGollapalli -- thanks for reporting! I can confirm this on Arch on current master. The fix I would propose is already in place and seemingly doesn't get the job done, so we'll have to think on how to proceed. 
For a temporary workaround, `vim` doesn't suffer the same issues, so if you change `$EDITOR` you should be able to edit your crontab without trouble.

**Comment by AGollapalli** [comment]
Thanks! I'll switch the default to vim.

**Comment by yamsu** [comment]
There seems to be a similar error when cd ing into a git directory. Esc results in "^[". The default configuration include prompt_vi_mode and powerline2, $EDITOR=vim

Hence, in a git directory the vi mode switching is broken. if one cd's out to a not git directory everything works as normal.

**Comment by AsafFisher** [comment]
This error is critical.

**Comment by anki-code** [comment]
I believe the #4283 should fix this. @acgollapalli @AsafFisher could you please test the case again on xonsh 0.11?

**Comment by yamsu** [comment]
I have updated xonsh to 0.11 through pip and I can confirm that the problem *persists*. On pressing escape in a git directory ^[ is displayed in the commandline. However, in a non git directory Esc works to switch to vim normal mode.

**Comment by yamsu** [comment]
@anki-code I just installed xonsh 1.5.1, with pip python 3.10.12, followed by xontrib-prompt-vi-mode via xpip. Unfortunately, I still have the same issue. In any git directory the Escape key results in '^[' rather than change to normal mode. In non git directories, I have no problem switching between insert and normal mode with the Esc key.

**Comment by yamsu** [comment]
@anki-code thanks for the above. I created the above docker instance and installed git and prompt-vi-mode. The latter is working fine in git and non-git directories. I checked the native installation and the issue seems to only occur when both powerline2 and prompt-vi-mode are enabled.

Working .xonshrc
```
xontrib load prompt_vi_mode
# xontrib load powerline2
```
