### ISSUE TITLE
pytest fails 8 tests

### ISSUE THREAD

**Issue by erezsh** [xonsh/xonsh#2881]
## xonfig
```markdown
+------------------+-----------------+
| xonsh            | 0.8.0           |
| Python           | 3.6.5           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 1.0.15          |
| shell type       | prompt_toolkit1 |
| pygments         | 2.2.0           |
| on posix         | True            |
| on linux         | True            |
| distro           | Fedora          |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

## Expected Behavior
The tests should pass, I believe.

## Current Behavior
pytest fails with the following tests:

* test_unmodified
* test_crud
* test_crud_path
* test_path
* test_sourcefile
* test_printname
* test_printfile
* test_activate

## Steps to Reproduce
```bash
$ cd xonsh
$ python3 -m pytest
```

## More info
```bash
$ python3 -m xonsh --version
xonsh/0.8.0

$ python3 -m pytest --version
This is pytest version 3.8.2, imported from /home/erez/.local/lib/python3.6/site-packages/pytest.py
setuptools registered plugins:
  xonsh-0.8.0 at /home/erez/xonsh/xonsh/pytest_plugin.py
  pytest-timeout-1.3.2 at /home/erez/.local/lib/python3.6/site-packages/pytest_timeout.py
  pytest-flake8-1.0.2 at /home/erez/.local/lib/python3.6/site-packages/pytest_flake8.py
  pytest-cov-2.6.0 at /home/erez/.local/lib/python3.6/site-packages/pytest_cov/plugin.py
```

**Comment by erezsh** [comment]
You can find the full output of pytest here: https://pastebin.com/tf43JNW4

**Comment by scopatz** [comment]
This should be fixed now on master.  Can you verify @erezsh? Thanks!

**Comment by erezsh** [comment]
Nope. Testing on commit `32ae5825`, I still get 9 errors (yes, one more than before)

**Comment by erezsh** [comment]
Yes

    ==================== 9 failed, 3057 passed, 26 skipped, 1 warnings in 21.56 seconds =====================

```bash
[erez@localhost xonsh]$ git lg | head
08364876 - Merge pull request #2890 from jay-tuckey/master (18 hours ago) <Anthony Scopatz>
1855e60e - Merge pull request #2923 from hmaarrfk/stacklevel (18 hours ago) <Anthony Scopatz>
```

**Comment by gforsyth** [comment]
It looks like a lot of these failures are due to some kind of naming mismatch for the python executable:

```
AssertionError: /usr/bin/env: ‘python3 -u’: No such file or directory
```

Just as a quick check, can you create a symlink called `python3` and see if the test failures clear up?

**Comment by erezsh** [comment]
I run the tests with `python3 -m pytest`, so python3 does exist.

**Comment by erezsh** [comment]
Also I'm getting `subprocess.CalledProcessError`, not AssertionError.

**Comment by erezsh** [comment]
Perhaps this is an issue with vox?

Here's part of the traceback?

```python
stdout = b'Traceback (most recent call last):\n  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main\n    "_...rno 2] No such file or directory: \'/usr/lib64/python3.6/ensurepip/_bundled/setuptools-39.0.1-py2.py3-none-any.whl\'\n'
stderr = None, retcode = 1
```

**Comment by gforsyth** [comment]
Can you post another pastebin of the runs? The previous one had a bunch of assertion errors

**Comment by laloch** [comment]
```
AssertionError: /usr/bin/env: ‘python3 -u’: No such file or directory
```
You cannot pass multiple arguments to `env` in shebang like this. You need to use `env -S`.
