### ISSUE TITLE
Getting the DeprecationWarning in 0.8.9

### ISSUE THREAD

**Issue by halloleo** [xonsh/xonsh#3014]
Same problem as in #2872 happens for me when installing 0.8.9 on macOS.

The exact error message is: 

```
.../lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py:943: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  collections.MutableMapping.register(ParseResults)
```

**Comment by halloleo** [comment]
Can be fixed by inserting at the beginning from `main(argv=None)` in `main.py` the following two lines:

        import warnings
        warnings.filterwarnings("ignore", category=DeprecationWarning)

This of course means that all DeprecationWarnings are omitted. But that is probably what we want for a user facing install of a shell, right?

**Comment by scopatz** [comment]
In the warning it states that this is coming from `pkg_resources` vending `pyparsing`. Are you importing something in your xonshrc that is touching `pkg_resources`?

**Comment by halloleo** [comment]
Mmmmh, the warning even happens without any `.xonshrc` file (when the wizard kicks in). Happens when started from bash (no interference from an underlying xonsh) and in a macOS Terminal window (no interference from `gnureadline` in Emacs).

I thought xonsh itself is importing pyparsing?

**Comment by scopatz** [comment]
Nope, xonsh doesn't use pyparsing directly

**Comment by halloleo** [comment]
But it happens without any .xonshrc! Why can that be?

**Comment by scopatz** [comment]
You might be using pygments which uses pkg_resources

**Comment by halloleo** [comment]
Sort of rings a bell... Will look into it.

However, the larger point is independent of *this* particular warning: Shouldn't DeprecationWarnings be generallyomitted on normal xonsh start-up? (E.g it could be enabled on debug start-up.)

**Comment by scopatz** [comment]
Yeah potentially, but we also want to see them so that they are fixed. PRs welcome!

**Comment by halloleo** [comment]
Back to this specific DeprecationWarning: It happens when you use `--shell-type ptk2` while `xonsh --shell-type readline` is fine.

**Comment by halloleo** [comment]
More to it: As it turns out this only happens on older _initial_ `xonsh` installs (<0.8.10). But with these the problem persists *even when you update it to the newest version*: Somehow the `prompt-toolkit` dependency file `../lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py` does not get updated despite `prompt-toolkit` beeing updated to the current version 2.0.8.

**Comment by gforsyth** [comment]
hrm.  can you post your `xonfig`?  I'm not sure if `prompt-toolkit` touches `pkg_resources`, I think you might need to update `pygments`

**Comment by halloleo** [comment]
Sure, the `xonfig` of the xonsh which shows the  warning on start up is

```
+------------------+---------------------+
| xonsh            | 0.8.10              |
| Git SHA          | 2cb42bdb            |
| Commit Date      | Feb 6 16:49:16 2019 |
| Python           | 3.7.1               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 2.0.8               |
| shell type       | prompt_toolkit2     |
| pygments         | None                |
| on posix         | True                |
| on linux         | False               |
| on darwin        | True                |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

As to `pygments`: It is not in the list of `pip freeze` in the venv I use for xonsh - which might  cause the strange behaviour that even updating xonsh doesn't resolve the issue while a new install into a completely fresh venv is fine.

**Comment by scopatz** [comment]
Is this still occuring?

**Comment by halloleo** [comment]
I will update to the current version and check.

**Comment by halloleo** [comment]
Upgraded xonsh to 0.9.6 and do not get the depreciation message.

**Comment by cshintov** [comment]
In case anyone getting this, just open up the file `.../prompt_toolkit/application/application.py`
and add the below two lines above the asyncio call.

```python
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning) 
```

**Comment by cshintov** [comment]
In case anyone getting this, just open up the file `.../prompt_toolkit/application/application.py`
and add the below two lines above the asyncio call.

Or you can add it in your `~/.xonshrc` file as well.

```python
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning) 
```
