### ISSUE TITLE
Crashing when using simple commands in alacritty.

### ISSUE THREAD

**Issue by seeralans** [xonsh/xonsh#3522]
## xonfig

<details>

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.9.14          |
| Python           | 3.8.2           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.5           |
| shell type       | prompt_toolkit2 |
| pygments         | 2.6.1           |
| on posix         | True            |
| on linux         | True            |
| distro           | arch            |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

</details>

## Current Behavior

Typing any commands e.g `ls` or `cat` will cause alacritty to crash when the arguments are being entered.
### Traceback (if applicable)

<details>

Alacritty Version: 0.4.2
```
traceback

Unhandled exception in event loop:
  File "/home/seeralan/.local/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 837, in in_term
    await _do_wait_for_enter("Press ENTER to continue...")
  File "/usr/lib/python3.8/contextlib.py", line 178, in __aexit__
    await self.gen.__anext__()
  File "/home/seeralan/.local/lib/python3.8/site-packages/prompt_toolkit/application/run_in_terminal.py", line 114, in in_terminal
    app._redraw()
  File "/home/seeralan/.local/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 523, in _redraw
    self.context.run(run_in_context)
  File "/home/seeralan/.local/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 509, in run_in_context
    self.renderer.render(self, self.layout)
  File "/home/seeralan/.local/lib/python3.8/site-packages/prompt_toolkit/renderer.py", line 568, in render
    layout.container.preferred_height(size.columns, size.rows).preferred,
  File "/home/seeralan/.local/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 324, in preferred_height
    dimensions = [
  File "/home/seeralan/.local/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 325, in <listcomp>
    c.preferred_height(width, max_available_height) for c in self._all_children
  File "/home/seeralan/.local/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 792, in preferred_height
    return self.content.preferred_height(width, max_available_height)
  File "/home/seeralan/.local/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 324, in preferred_height
    dimensions = [
  File "/home/seeralan/.local/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 325, in <listcomp>
    c.preferred_height(width, max_available_height) for c in self._all_children
  File "/home/seeralan/.local/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 2595, in preferred_height
    return self.content.preferred_height(width, max_available_height)
  File "/home/seeralan/.local/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 1620, in preferred_height
    return self._merge_dimensions(
  File "/home/seeralan/.local/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 1648, in _merge_dimensions
    preferred = get_preferred()
  File "/home/seeralan/.local/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 1613, in preferred_content_height
    return self.content.preferred_height(
  File "/home/seeralan/.local/lib/python3.8/site-packages/prompt_toolkit/layout/controls.py", line 639, in preferred_height
    content = self.create_content(width, height=1)  # Pass a dummy '1' as height.
  File "/home/seeralan/.local/lib/python3.8/site-packages/prompt_toolkit/layout/controls.py", line 787, in create_content
    cursor_position=translate_rowcol(
  File "/home/seeralan/.local/lib/python3.8/site-packages/prompt_toolkit/layout/controls.py", line 770, in translate_rowcol
    return Point(x=get_processed_line(row).source_to_display(col), y=row)
  File "/home/seeralan/.local/lib/python3.8/site-packages/prompt_toolkit/layout/controls.py", line 716, in get_processed_line
    processed_line = transform(i, get_line(i))
  File "/home/seeralan/.local/lib/python3.8/site-packages/prompt_toolkit/lexers/pygments.py", line 319, in get_line
    for num, line in generator:
  File "/home/seeralan/.local/lib/python3.8/site-packages/prompt_toolkit/lexers/pygments.py", line 270, in create_line_generator
    yield from enumerate(split_lines(list(get_text_fragments())), start_lineno)
  File "/home/seeralan/.local/lib/python3.8/site-packages/prompt_toolkit/lexers/pygments.py", line 268, in get_text_fragments
    yield _token_cache[t], v
  File "/home/seeralan/.local/lib/python3.8/site-packages/prompt_toolkit/lexers/pygments.py", line 141, in __missing__
    result = "class:" + pygments_token_to_classname(key)
  File "/home/seeralan/.local/lib/python3.8/site-packages/prompt_toolkit/styles/pygments.py", line 66, in pygments_token_to_classname
    parts = ("pygments",) + token

Exception can only concatenate tuple (not "NoneType") to tuple
Press ENTER to continue...
```

</details>

## Steps to Reproduce

1. Open xonsh using alacritty
2. enter `$ ls ~`

**Comment by gotgenes** [comment]
@seeralans I noticed your version of xonsh is a little outdated. The current version is 0.9.17. Are you able to install the latest version, and do you still experience this issue with it? You can also try starting xonsh with

```
xonsh --no-rc
```

and see if you're still seeing this same error.

**Comment by seeralans** [comment]
It was the old version was the issue, the new version works great, thanks.

**Comment by hroemer** [comment]
This issue is still present in version 0.9.17:

## xonfig

```
+------------------+---------------------+
| xonsh            | 0.9.17.dev2         |
| Git SHA          | 97a921c7            |
| Commit Date      | Apr 8 14:48:23 2020 |
| Python           | 3.8.2               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 3.0.5               |
| shell type       | prompt_toolkit2     |
| pygments         | 2.6.1               |
| on posix         | True                |
| on linux         | True                |
| distro           | manjaro             |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

## traceback

```
Unhandled exception in event loop:
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/eventloop/utils.py", line 72, in schedule
    func()
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 456, in redraw
    self._redraw()
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 523, in _redraw
    self.context.run(run_in_context)
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 509, in run_in_context
    self.renderer.render(self, self.layout)
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/renderer.py", line 568, in render
    layout.container.preferred_height(size.columns, size.rows).preferred,
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 324, in preferred_height
    dimensions = [
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 325, in <listcomp>
    c.preferred_height(width, max_available_height) for c in self._all_children
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 792, in preferred_height
    return self.content.preferred_height(width, max_available_height)
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 324, in preferred_height
    dimensions = [
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 325, in <listcomp>
    c.preferred_height(width, max_available_height) for c in self._all_children
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 2595, in preferred_height
    return self.content.preferred_height(width, max_available_height)
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 1620, in preferred_height
    return self._merge_dimensions(
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 1648, in _merge_dimensions
    preferred = get_preferred()
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 1613, in preferred_content_height
    return self.content.preferred_height(
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/controls.py", line 639, in preferred_height
    content = self.create_content(width, height=1)  # Pass a dummy '1' as height.
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/controls.py", line 761, in create_content
    document = buffer.document
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/buffer.py", line 524, in document
    return self._document_cache[
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/cache.py", line 98, in __missing__
    result = self.get_value(*key)
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/document.py", line 98, in __init__
    assert cursor_position is None or cursor_position <= len(text), AssertionError(

Exception cursor_position=2, len_text=1
Press ENTER to continue...
```

I removed ``.xonshrc`` (should be equivalent to argument ``--no-rc``) but unfortunately to no avail.
Is this related to #3101?

**Comment by gotgenes** [comment]
@hroemer  It looks like you're running a pre-release version of xonsh:

>```
>+------------------+---------------------+
>| xonsh            | 0.9.17.dev2         |
>| Git SHA          | 97a921c7            |
>| Commit Date      | Apr 8 14:48:23 2020 |
>```

It should look like this, instead:

```                   
+------------------+-----------------+
| xonsh            | 0.9.17          |
```

I'm not sure how you ended up with a pre-release version installed, but you should try installing xonsh from a release package.

**Comment by hroemer** [comment]
@gotgenes I uninstalled xonsh and cleared the `.cache/pip` folder before installing it again, but the `xonsh-0.9.17.tar.gz` seems to have a dev wheel inside:

```
pip install --user --upgrade xonsh                                                                                                                                                                                            
Collecting xonsh
  Downloading xonsh-0.9.17.tar.gz (984 kB)
     |████████████████████████████████| 984 kB 1.3 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: xonsh
  Building wheel for xonsh (PEP 517) ... done
  Created wheel for xonsh: filename=xonsh-0.9.17.dev2-py3-none-any.whl size=813373 sha256=b982e6bd4032d81f07f72162b24c7aa331e2bab7b816b01eb0f8fa969c102503
  Stored in directory: /home/user/.cache/pip/wheels/70/45/3c/9030d94c4da65cba29a4e614b8560dcd2762cabd5522c16379
Successfully built xonsh
Installing collected packages: xonsh
  Attempting uninstall: xonsh
    Found existing installation: xonsh 0.9.17.dev2
    Uninstalling xonsh-0.9.17.dev2:
      Successfully uninstalled xonsh-0.9.17.dev2
Successfully installed xonsh-0.9.17.dev2
```
Please have a look at https://files.pythonhosted.org/packages/b8/70/c43e9a44238711d7bc4d35abbdf853881ad911e6c07bbf93afc164ba02ec/xonsh-0.9.17.tar.gz , the package file `__init__.py` contains  `__version__ = "0.9.17.dev2"`. Thus I guess it is part of the [public release](https://pypi.org/project/xonsh/#files).

**Comment by gforsyth** [comment]
Hey @hroemer -- looks like our last release was a little off.  Thanks for investigating that.  I've just released 0.9.18.

**Comment by hroemer** [comment]
@gforsyth thanks for the quick release.

I experimented with different combinations (user installation vs. system installation) but the error still occurs. I think it is a timing (cache construction / history / line length?!) issue.
I can force this error by opening multiple alacritty sessions (i3 shortcut) and then picking e.g. change dir commands to some subfolder from my history. This triggers in most cases. If I wait let's say 5 to 10s it will not occur in that particular terminal session at all!?
If I uninstall `prompt_toolkit`, the error obviously disappears.

Is there away I could further trace it down?

**Comment by gforsyth** [comment]
I would first check upstream with prompt toolkit to see if it's a known issue. 
If it hasn't been reported, then maybe see if the can trigger the same error using one of the prompt toolkit simple examples (since that will make it easier to debug)

**Comment by hroemer** [comment]
@gforsyth thanks for your suggestion. I double-checked the issue list of `prompt_toolkit` and it has already been reported in prompt-toolkit/python-prompt-toolkit#1119.
