### ISSUE TITLE
Hints for the `dd` command do not work properly.

### ISSUE THREAD

**Issue by WojAbuk** [xonsh/xonsh#4746]
When I use a prompt, I expect the path to be completed, but instead the entire path is appended to the end of what I have already written. I have not noticed this with other commands. So I think this is only a problem with the `dd` command.
## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
Thanks for reporting @WojAbuk -- I think this has been fixed on `main` -- can you try out installing from `main` and see if that fixes your issue?

We're overdue for a release, too -- I'll leave this open until we confirm whether or not it's fixed.

**Comment by WojAbuk** [comment]
I installed xonsh-git for AUR (previously I had the binary from the arch repository installed). The same error occurs on both versions. I do not know if this is the main version and I do not know how to install a newer version than in AUR, if there is one.

**Comment by yaxollum** [comment]
Hi @gforsyth I just checked, and this is still an issue on `main`.
