### ISSUE TITLE
xonsh not installable with pip from git or source anymore

### ISSUE THREAD

**Issue by dev2718** [xonsh/xonsh#4807]
Up to e62c0e9cec376e73ae2719803d9a88eeec68be19 xonsh could be installed with pip and git like this:

```sh
pip3 uninstall xonsh
pip3 install git+https://github.com/xonsh/xonsh@e62c0e9cec376e73ae2719803d9a88eeec68be19
```

With the commit after that (ed4421ddf4b4b0a131a00075e1ea29e04aaf3fa0), this no longer works
```sh
pip3 uninstall xonsh
pip3 install git+https://github.com/xonsh/xonsh@ed4421ddf4b4b0a131a00075e1ea29e04aaf3fa0
```

The result is:
```
...
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
Successfully installed UNKNOWN-0.0.0
```

**Comment by gforsyth** [comment]
Thanks for reporting @dev2718 -- I think pip added pep621 support quite recently, so can you try upgrading `pip` and see if that sorts it?

**Comment by dev2718** [comment]
> Thanks for reporting @dev2718 -- I think pip added pep621 support quite recently, so can you try upgrading `pip` and see if that sorts it?

The behaviour persists on the most recent version of pip (22.0.4), tested on Ubuntu Server ARM 22.04.

**Comment by gforsyth** [comment]
Hmm, can you try upgrading `wheel`?

```
pip install git+https://github.com/xonsh/xonsh@ed4421dd
Collecting git+https://github.com/xonsh/xonsh@ed4421dd
  Cloning https://github.com/xonsh/xonsh (to revision ed4421dd) to /tmp/pip-req-build-t06m2ce5
  Running command git clone --filter=blob:none -q https://github.com/xonsh/xonsh /tmp/pip-req-build-t06m2ce5
  WARNING: Did not find branch or tag 'ed4421dd', assuming revision or ref.
  Running command git checkout -q ed4421dd
  Resolved https://github.com/xonsh/xonsh to commit ed4421dd
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: xonsh
  Building wheel for xonsh (pyproject.toml) ... done
  Created wheel for xonsh: filename=xonsh-0.12.4-py310-none-any.whl size=894224 sha256=19e11c0236d3810e4bb7be80531ab11231add8a245c7007845936076f9df987d
  Stored in directory: /tmp/pip-ephem-wheel-cache-qh6w5nsz/wheels/4e/79/f7/c11b77d56f6eb30cfe9956b4b0983abd7a49ffec6e69540819
Successfully built xonsh
Installing collected packages: xonsh
Successfully installed xonsh-0.12.4
```

**Comment by dev2718** [comment]
Strange... My wheel version is 0.37.1, the most recent.

**Comment by jnoortheen** [comment]
this is from the above docker container, using latest pip (22.1) correctly installs.

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/6702219/168083868-1563941f-e4d6-429c-bdda-d650a325f929.png">

**Comment by PythonCoderAS** [comment]
This is still true with xonsh 0.12.5. Using `pip install --verbose --upgrade --force --no-binary :all: xonsh` forces pip to go to 0.12.4 in order to get a working install.

**Comment by gforsyth** [comment]
thanks for flagging @PythonCoderAS -- we had a release hiccough and the metadata on the tarball is wrong, which is why `pip` is falling back to 0.12.4.  I'll cut a new point release to resolve.

**Comment by gforsyth** [comment]
@PythonCoderAS -- I've just released 0.12.6 and confirmed that it can be installed using `pip install --verbose --upgrade --force --no-binary :all: xonsh` -- sorry for the issues packaging it downstream.

**Comment by dev2718** [comment]
@gforsyth The original issue still persists with current master:

``bash
docker run -it ubuntu:22.04

apt update
apt install python3-pip git
pip3 install git+https://github.com/xonsh/xonsh@5401a246
``

**Comment by dev2718** [comment]
@gforsyth It is still reproducible with the newest version of pip (22.1.2):

```bash
apt update
apt install python3-pip git
pip install --upgrade pip
pip3 install git+https://github.com/xonsh/xonsh@5401a246
```

**Comment by gforsyth** [comment]
wow, that's _really_ annoying.  reopening...

**Comment by PythonCoderAS** [comment]
@dev2718 out of curiosity what is your version of setuptools? Ran into a _really annoying_ bug on Homebrew where the venvs created by them have an out-of-date version of setuptools and need to be upgraded.

**Comment by PythonCoderAS** [comment]
The plot gets thicker: I can install successfully from a venv, but not direct by the system.

**Comment by jnoortheen** [comment]
This is mostly an issue with pip+ubuntu . It works with the `python:3-slim` image without any changes.

it can be fixed by install setuptools separately

```sh
# upgrade the setuptools.
pip3 install -U setuptools
# or  uninstalling it also will work.
pip3 uninstall setuptools

# now this will use correct version of setuptools and will detect name and version
pip3 install git+https://github.com/xonsh/xonsh@main
```

I am closing this as this is an issue of that system package management. Similar discussions can be found at https://discuss.python.org/t/pip-without-setuptools-could-the-experience-be-improved/11810/2
